[theme]
base = "dark"
primaryColor = "#60A5FA"
backgroundColor = "#1A1E29"
secondaryBackgroundColor = "#222734"
textColor = "#E5E7EB"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
